#!/bin/sh
if [ -f /usr/share/java-utils/java-functions ] ; then
  . /usr/share/java-utils/java-functions
  set_jvm
  set_javacmd
fi

export M2_HOME=/usr/share/maven
echo $JAVA_HOME
export JAVA_HOME
# can't put it on command line due to
# http://jira.codehaus.org/browse/SUREFIRE-121
export MAVEN_OPTS="-Dmaven.local.mode ${local_add}"
echo "Running mvn in local mode. Please report bugs to http://bugzilla.redhat.com"

$M2_HOME/bin/mvn "$@"
